"""STCP conversion model (paper §3.1).

t* = argmax_t P(t) over the candidate set T generated by
  1. word conversion: jieba segmentation + word look-up table (§3.1.1)
  2. character conversion: every candidate of every remaining character (§3.1.2)
scored by a character-level n-gram LM (KenLM, §3.1.3). T is exponential, so we
search it with a beam over the lattice, recombining hypotheses whose last
(order-1) characters coincide (exact for an n-gram LM when the beam is wide enough).
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path

import jieba
import kenlm

from .tables import load_char_table, load_custom_table, load_word_table

jieba.setLogLevel(60)
SENT_SPLIT = re.compile(r"(?<=[。！？；\n])")


@dataclass
class Segment:
    src: str
    cands: list[str]            # candidate target strings, first = table default
    kind: str                   # "word" | "char" | "fixed"
    out: str = ""
    probs: list[float] = field(default_factory=list)  # LM posterior over cands (for proofreading)


class Converter:
    def __init__(
        self,
        lm_path: str | Path,
        word_mode: str = "tw",
        char_table: dict[str, list[str]] | None = None,
        custom_tables: list[str | Path] = (),
        beam: int = 10,
    ) -> None:
        self.lm = kenlm.Model(str(lm_path))
        self.order = self.lm.order
        self.beam = beam
        self.char_table = char_table or load_char_table()
        self.word_table = load_word_table(word_mode)
        for path in custom_tables:
            self.word_table.update(load_custom_table(path))
        self.tokenizer = jieba.Tokenizer()
        if self.word_table:
            self.tokenizer.initialize()
            for w in self.word_table:
                if len(w) > 1:
                    self.tokenizer.add_word(w, freq=max(self.tokenizer.FREQ.get(w, 0), 3000))

    # -- lattice -------------------------------------------------------------
    def lattice(self, text: str) -> list[Segment]:
        segs: list[Segment] = []
        words = self.tokenizer.cut(text, HMM=False) if self.word_table else text
        for w in words:
            if len(w) > 1 and w in self.word_table:
                segs.append(Segment(w, self.word_table[w], "word"))
                continue
            for c in w:
                cands = self.char_table.get(c)
                if cands and len(cands) > 1:
                    segs.append(Segment(c, cands, "char"))
                else:
                    segs.append(Segment(c, cands or [c], "fixed"))
        return segs

    # -- search --------------------------------------------------------------
    def _extend(self, state: kenlm.State, s: str) -> tuple[float, kenlm.State]:
        total = 0.0
        for ch in s:
            if ch.isspace():
                continue
            nxt = kenlm.State()
            total += self.lm.BaseScore(state, ch, nxt)
            state = nxt
        return total, state

    def decode(self, segs: list[Segment]) -> None:
        start = kenlm.State()
        self.lm.BeginSentenceWrite(start)
        # hyp: key -> (score, state, choices)
        hyps: dict[str, tuple[float, kenlm.State, tuple[int, ...], str]] = {"": (0.0, start, (), "")}
        k = self.order - 1
        for seg in segs:
            new: dict[str, tuple[float, kenlm.State, tuple[int, ...], str]] = {}
            for score, state, choices, hist in hyps.values():
                for i, cand in enumerate(seg.cands):
                    delta, st = self._extend(state, cand)
                    h = (hist + cand.replace(" ", ""))[-k:]
                    s = score + delta
                    if h not in new or new[h][0] < s:
                        new[h] = (s, st, choices + (i,), h)
            if len(new) > self.beam:
                new = dict(sorted(new.items(), key=lambda kv: -kv[1][0])[: self.beam])
            hyps = new
        best = max(hyps.values(), key=lambda v: v[0] + self.lm.BaseScore(v[1], "</s>", kenlm.State()))
        for seg, i in zip(segs, best[2]):
            seg.out = seg.cands[i]

    def convert_sentence(self, text: str) -> list[Segment]:
        segs = self.lattice(text)
        self.decode(segs)
        return segs

    def convert(self, text: str) -> str:
        return "".join(seg.out for part in SENT_SPLIT.split(text) if part for seg in self.convert_sentence(part))

    # -- proofreading support --------------------------------------------------
    def score_alternatives(self, segs: list[Segment]) -> None:
        """Posterior over each ambiguous segment's candidates, all else fixed at the best path."""
        outs = [s.out for s in segs]
        for idx, seg in enumerate(segs):
            if len(seg.cands) < 2:
                continue
            logps = []
            for cand in seg.cands:
                outs[idx] = cand
                logps.append(self.lm.score(" ".join(c for c in "".join(outs) if not c.isspace())))
            outs[idx] = seg.out
            m = max(logps)
            ps = [10 ** (lp - m) for lp in logps]
            z = sum(ps)
            seg.probs = [p / z for p in ps]

    def annotate(self, text: str) -> list[dict]:
        result = []
        for part in SENT_SPLIT.split(text):
            if not part:
                continue
            segs = self.convert_sentence(part)
            for s in segs:  # let proofreaders fall back to plain character conversion of a mapped word
                if s.kind == "word":
                    plain = "".join(self.char_table.get(c, [c])[0] for c in s.src)
                    if plain not in s.cands:
                        s.cands = s.cands + [plain]
            self.score_alternatives(segs)
            result.extend(
                {"src": s.src, "out": s.out, "kind": s.kind, "cands": s.cands, "probs": s.probs} for s in segs
            )
        return result


class MostFrequent:
    """Baseline: pick the candidate most frequent in the training corpus (cf. Zhang 2011)."""

    def __init__(self, freq: dict[str, int], char_table: dict[str, list[str]] | None = None) -> None:
        self.table = char_table or load_char_table()
        self.freq = freq

    def convert(self, text: str) -> str:
        out = []
        for c in text:
            cands = self.table.get(c, [c])
            out.append(max(cands, key=lambda t: self.freq.get(t, 0)) if len(cands) > 1 else cands[0])
        return "".join(out)

